// constants/pricingPackages.js

const pricingPackages = [
    {
      title: "Normal Listing",
      price: 6000,
      recommended: false,
      description: "A basic listing package suitable for small property sellers who want exposure on our platform for 3 months.",
      features: [
        "3 High Quality image of property",
        "1 High Quality Drone Video of property",
        "Property Description",
        "Listed in website,youtube, tiktok and facebook",
        "Facebook Sponsored Promotion for 7 days",
        "Listing visibility for 3 months",
        "Standard support",
      ],
    },
    {
      title: "Featured Listing",
      price: 10000,
      recommended: false,
      description: "Ideal for serious sellers looking to boost visibility with a longer promotion and more reach on Facebook.",
      features: [
        "5 High Quality images of property",
        "1 High Quality Drone Video of property",
        "Property Description",
        "Listed in website,youtube, tiktok and facebook",
        "Facebook Sponsored Promotion for 15 days",
        "Listing visibility for 4 months",
        "Priority support",
        "Highlighted in search results",
      ],
    },
    {
      title: "Premium Listing",
      price: 20000,
      recommended: true,
      description: "Our most popular plan with maximum visibility, social reach, and priority placement across the platform.",
      features: [
        "10 High Quality images of property",
        "1 High Quality Drone Video of property",
        "Property Description",
        "Facebook Sponsored Promotion for 30 days",
        "Listing visibility for 6 months",
        "Priority support",
        "Listed in website,youtube, tiktok and facebook",
        "Local agents support untill sold",
        "Highlighted in search results",
        "Priority placement on homepage",
        "Share on Instagram and TikTok",
      ],
    },
    {
      title: "Top Listing",
      price: 32000,
      recommended: false,
      description: "Designed for premium properties needing extended marketing and maximum audience reach for serious buyers.",
      features: [
        "15 High Quality images of property",
        "1 High Quality Drone Video of property",
        "Property Description",
        "Facebook Sponsored Promotion for 45 days",
        "Listing visibility for 10 months",
        "Dedicated account manager",
        "Listed in website,youtube, tiktok and facebook",
        "Priority placement on homepage",
        "Video ad creation & promotion on tiktok",
        "Share on Instagram, TikTok, LinkedIn",
      ],
    },
  ];
  export default pricingPackages;