import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import "@fortawesome/fontawesome-free/css/all.min.css";
import "./globals.css"; // keep your global styles here
import AppProvider from "@/redux/provider";
import MainLayout from "@/layouts/MainLayout";



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Lele Sasto GharJagga Karobar Kendra",
  description: "Generated by create next app",
  keywords: "Sasto GharJagga, land for sale at lele, land for rent at lele, lalitpur",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" >
     
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AppProvider>
          <MainLayout>
        <Header/>
        {children}
        <Footer/>
        </MainLayout>
        </AppProvider>
      </body>
    </html>
  );
}